Metrics Support + Image Upgrade
daichi703n/elastalert-helm pull request #4
Opened 2023-03-17 19:01 UTC by k4kratik

### What it brings to the table : 
Existing latest image of praeco/elastalert-server has capability to expose metrics on a port, unfortunately this helm chart is quite outdated and does not support that. We can leverage that to setup some interesting alerts based on those metrics. 

I have enabled that support in this helm chart by adding that port in service and deployment.
It is totally optional and you can render this change in your env with the help of a flag in `values.yaml` file.
e.g.
```
metrics:
  enabled: true
  port: 9979
```

default port is 9979 of the container and for the service you can override that using above config.

### Todo:
1. ServiceMonitor
2. Prometheus Rule
3. README

2023-03-17 19:26 UTC, k4kratik commented
@daichi703n - I have upgraded the image as per the official repo as I think your image does not support.
Here, https://github.com/jertel/elastalert2/pull/75 ,they have introduced support of prometheus metrics endpoint.
Thanks again for developing and sharing this helm chart.

2023-03-21 17:27 UTC, daichi703n requested changes
@k4kratik Thanks for using this helm chart.
Image tag should be quoted.

2023-03-21 17:27 UTC, daichi703n commented on values.yaml
> +  tag: 20230219
```suggestion
  tag: "20230219"
```

2023-03-21 17:27 UTC, daichi703n commented on values.yaml
> +  tag: 20230219
Without quote, tag will be handled as number and fail to pull. )`image tag "praecoapp/elastalert-server:2.0230219e+07"`)

```
kubectl describe pod/elastalert-79fcd5cc4d-5m4d6
---
...
  Warning  Failed                  4m53s (x10 over 6m30s)  kubelet                  Error: InvalidImageName
  Warning  InspectFailed           86s (x25 over 6m30s)    kubelet                  Failed to apply default image tag "praecoapp/elastalert-server:2.0230219e+07": couldn't parse image reference "praecoapp/elastalert-server:2.0230219e+07": invalid reference format
```

2023-03-21 17:27 UTC, daichi703n commented on templates/service.yaml
> +    {{- end}}
```suggestion
    {{- end }}
```

2023-03-22 10:47 UTC, k4kratik commented
Changes done as per the suggestions, Can you check now ?
Thanks. @daichi703n

2023-03-23 06:33 UTC, daichi703n approved these changes
LGTM

2023-03-23 06:34 UTC, merged

2023-03-23 06:38 UTC, k4kratik commented
Thanks 🚀 @daichi703n

2023-03-23 06:40 UTC, daichi703n commented
@k4kratik Thanks.
From now on, I will proceed with the version up of the Helm Package.